🔖 3.4.0, FieldMaskAttribute
MONQDL/Monq.Core.MvcExtensions pull request #11
Opened 2023-01-19 11:23 UTC by IlyaLykov

Реализован аттрибут для сериализации ответа с учетом gRpc.FieldMask.

2023-01-19 13:05 UTC, aligin commented
Отличный атритут!

Есть несколько вопросов и замечаний:

1. А как быть с проектами, которые используют `System.Text.Json`?
2. Это новый функционал - версия должна увеличивать среднюю цифру.
3. Коммиты в github репах, пожалуйста, пиши на ангельском.

2023-01-19 14:59 UTC, 2nnar requested changes

2023-01-19 14:59 UTC, 2nnar commented on src/Monq.Core.MvcExtensions/Filters/FieldMaskFilterAttribute.cs
> +    public class FieldMaskFilterAttribute : ActionFilterAttribute
Из семантических соображений возможно стоит поменять название просто на `FieldMaskAttribute`, т.к. далеко не факт, что маска будет применяться только к неким API фильтрации.

2023-01-19 14:59 UTC, 2nnar commented on src/Monq.Core.MvcExtensions/Filters/FieldMaskFilterAttribute.cs
> +        }
Хорошо бы вынести общий с `ArrayInputAttribute` функционал в какой-нибудь отдельный класс-helper. Практически полностью дублировать код ни к чему.

2023-01-19 14:59 UTC, 2nnar commented on src/Monq.Core.MvcExtensions/Filters/FieldMaskFilterAttribute.cs
> +                NewtonsoftJsonSerializerSettingsHelper.DeepCopy(jsonOptions.Value.SerializerSettings);
Перенос строк в тернарном операторе видится читаемей в таком формате:
```
var x = condition
    ? then
    : else;
```
P.S.: только если в одну строку не получится записать.

2023-01-19 14:59 UTC, 2nnar commented on src/Monq.Core.MvcExtensions/Filters/FieldMaskFilterAttribute.cs
> +            var modelType = GetModelType(objectResult.Value.GetType());
`objectResult.Value` надо на всякий случай проверять на `null`.

2023-01-19 14:59 UTC, 2nnar commented on src/Monq.Core.MvcExtensions/Filters/FieldMaskFilterAttribute.cs
> +                mvcOptions is not null ? mvcOptions.Value : new MvcOptions());
В сборках версии .NET 6 и 7 тут используется устаревший конструктор formatter'а. В актуальном конструкторе можно передать отдельно опции сериалайзера и MVC, что позволяет на самом деле не объединять настройки с копированием заранее. Для обратной совместимости наверное пока можно оставить как есть, но напиши комментарий в коде на будущее, чтоб при отказе от поддержки старых версий платформы можно было упростить эту штуку.

2023-01-19 14:59 UTC, 2nnar commented on src/Monq.Core.MvcExtensions/Filters/FieldMaskFilterAttribute.cs
> +        public FieldMaskFilterAttribute(params string[] parameterName)
Раз уж атрибут полностью посвящён field маске, то на входе по идее не должно быть массива параметров.
Думаю, можно оставить возможность передачи **одного** названия параметра запроса - значение `fieldMask` по умолчанию, но с возможностью переопределения.

2023-01-19 14:59 UTC, 2nnar commented on src/Monq.Core.MvcExtensions/Filters/FieldMaskFilterAttribute.cs
> +            var jsonOptions = context.HttpContext.RequestServices.GetService<IOptions<MvcNewtonsoftJsonOptions>>();
В качестве предложения по поддержке и NewtonsoftJson, и System.Text.Json - может быть форматтер определять в зависимости от нахождения тех или иных опций? И по умолчанию сделать именно System.Text.Json. Но для начала, конечно, надо разобраться, можно ли в System.Text.Json так же элегантно пропустить сериализацию свойств модели. Глобально основные потребности пока покрываются, но если можно заложиться на будущее сразу, то почему бы и нет.

2023-01-20 03:50 UTC, IlyaLykov commented on src/Monq.Core.MvcExtensions/Filters/FieldMaskFilterAttribute.cs
> +            var jsonOptions = context.HttpContext.RequestServices.GetService<IOptions<MvcNewtonsoftJsonOptions>>();
Аналогичный механизм для System.Text.Json завезли только в .Net 7 (https://devblogs.microsoft.com/dotnet/system-text-json-in-dotnet-7/). Либа поддерживает версии, начиная с netcore 3.1, что делает невозможным использовать данный механизм. 
Чтобы использовать динамический форматтер для System.Text.Json нужно писать кастомный дженерик json конвертер для типов (https://www.appsloveworld.com/csharp/100/2255/system-text-json-conditionally-ignore-property-on-runtime.)

2023-01-20 06:36 UTC, 2nnar commented on src/Monq.Core.MvcExtensions/Filters/FieldMaskFilterAttribute.cs
> +            var jsonOptions = context.HttpContext.RequestServices.GetService<IOptions<MvcNewtonsoftJsonOptions>>();
Обсудили варианты, решили доделать System.Text.Json потом. Нужно написать TODO.

2023-01-20 06:42 UTC, aligin commented on src/Monq.Core.MvcExtensions/Filters/FieldMaskFilterAttribute.cs
> +            var jsonOptions = context.HttpContext.RequestServices.GetService<IOptions<MvcNewtonsoftJsonOptions>>();
3.1 можно выбросить смело.
А какой механизм отсутствует?

2023-01-20 06:57 UTC, IlyaLykov commented on src/Monq.Core.MvcExtensions/Filters/FieldMaskFilterAttribute.cs
> +            var jsonOptions = context.HttpContext.RequestServices.GetService<IOptions<MvcNewtonsoftJsonOptions>>();
Нельзя делать кастомный резолвер для сериализатора, как в NewtonSoftJson.

2023-01-27 06:24 UTC, 2nnar approved these changes

2023-01-27 06:36 UTC, merged